<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">document2LogTrace</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWQgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCklEYXRhIHJlYyA9IElEYXRh
VXRpbC5nZXRJRGF0YSggaWQsICJyZWNvcmQiICk7DQppZC5kZXN0cm95KCk7DQoNClN0cmluZyB0
cmFjZVRleHQgPSBudWxsOw0KaWYgKCBudWxsICE9IHJlYyApeyANCglqYXZhLmlvLlN0cmluZ1dy
aXRlciBzID0gbmV3IGphdmEuaW8uU3RyaW5nV3JpdGVyKCk7DQoJd3JpdGVMb2dUcmFjZSgicmVj
b3JkIiwgcmVjLCAwLCBzLCB0cnVlKTsNCgl0cmFjZVRleHQgPSBzLnRvU3RyaW5nKCk7DQp9DQoN
Ci8vIHBpcGVsaW5lDQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdldEN1
cnNvcigpOw0KSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3IsICJ0cmFjZVRleHQiLCB0cmFj
ZVRleHQpOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOwkJCQ==</value>
</Values>
